import type { Category, CategoryKind } from "./types";

// The canonical category list. Colors are used consistently across every chart.
export const CATEGORIES: Category[] = [
  { name: "Income", kind: "income", color: "#16a34a" },
  { name: "Transfer", kind: "transfer", color: "#64748b" },
  { name: "Housing", kind: "expense", color: "#7c3aed" },
  { name: "Groceries", kind: "expense", color: "#0891b2" },
  { name: "Dining", kind: "expense", color: "#ea580c" },
  { name: "Transportation", kind: "expense", color: "#2563eb" },
  { name: "Utilities", kind: "expense", color: "#0d9488" },
  { name: "Subscriptions", kind: "expense", color: "#db2777" },
  { name: "Shopping", kind: "expense", color: "#d97706" },
  { name: "Health", kind: "expense", color: "#dc2626" },
  { name: "Entertainment", kind: "expense", color: "#9333ea" },
  { name: "Travel", kind: "expense", color: "#0284c7" },
  { name: "Fees & Interest", kind: "expense", color: "#b91c1c" },
  { name: "Other", kind: "expense", color: "#94a3b8" },
];

export const CATEGORY_NAMES = CATEGORIES.map((c) => c.name);

export function categoryColor(name: string): string {
  return CATEGORIES.find((c) => c.name === name)?.color ?? "#94a3b8";
}

export function categoryKind(name: string): CategoryKind {
  return CATEGORIES.find((c) => c.name === name)?.kind ?? "expense";
}

// Default keyword rules. `pattern` is matched as a lowercase substring of the
// transaction description/merchant. Lower priority number wins.
export const DEFAULT_RULES: { pattern: string; category: string; priority: number }[] = [
  { pattern: "payroll", category: "Income", priority: 10 },
  { pattern: "direct dep", category: "Income", priority: 10 },
  { pattern: "deposit", category: "Income", priority: 60 },
  { pattern: "transfer to", category: "Transfer", priority: 10 },
  { pattern: "transfer from", category: "Transfer", priority: 10 },
  { pattern: "autopay", category: "Transfer", priority: 15 },
  { pattern: "automatic payment", category: "Transfer", priority: 12 },
  { pattern: "payment thank you", category: "Transfer", priority: 12 },
  { pattern: "online payment thank you", category: "Transfer", priority: 15 },
  { pattern: "credit crd", category: "Transfer", priority: 15 },
  { pattern: "cardmember serv", category: "Transfer", priority: 15 },
  { pattern: "rent", category: "Housing", priority: 20 },
  { pattern: "mortgage", category: "Housing", priority: 20 },
  { pattern: "landlord", category: "Housing", priority: 20 },
  { pattern: "whole foods", category: "Groceries", priority: 20 },
  { pattern: "wholefds", category: "Groceries", priority: 20 },
  { pattern: "trader joe", category: "Groceries", priority: 20 },
  { pattern: "tj maxx", category: "Shopping", priority: 20 },
  { pattern: "safeway", category: "Groceries", priority: 20 },
  { pattern: "kroger", category: "Groceries", priority: 20 },
  { pattern: "aldi", category: "Groceries", priority: 20 },
  { pattern: "costco", category: "Groceries", priority: 30 },
  { pattern: "grocery", category: "Groceries", priority: 40 },
  { pattern: "starbucks", category: "Dining", priority: 20 },
  { pattern: "chipotle", category: "Dining", priority: 20 },
  { pattern: "doordash", category: "Dining", priority: 20 },
  { pattern: "uber eats", category: "Dining", priority: 20 },
  { pattern: "restaurant", category: "Dining", priority: 40 },
  { pattern: "coffee", category: "Dining", priority: 40 },
  { pattern: "shell", category: "Transportation", priority: 20 },
  { pattern: "chevron", category: "Transportation", priority: 20 },
  { pattern: "exxon", category: "Transportation", priority: 20 },
  { pattern: "uber", category: "Transportation", priority: 35 },
  { pattern: "lyft", category: "Transportation", priority: 20 },
  { pattern: "parking", category: "Transportation", priority: 30 },
  { pattern: "transit", category: "Transportation", priority: 30 },
  { pattern: "geico", category: "Transportation", priority: 15 },
  { pattern: "auto insurance", category: "Transportation", priority: 15 },
  { pattern: "car insurance", category: "Transportation", priority: 15 },
  { pattern: "state farm", category: "Transportation", priority: 20 },
  { pattern: "progressive ins", category: "Transportation", priority: 20 },
  { pattern: "allstate", category: "Transportation", priority: 20 },
  { pattern: "pg&e", category: "Utilities", priority: 20 },
  { pattern: "electric", category: "Utilities", priority: 25 },
  { pattern: "comcast", category: "Utilities", priority: 20 },
  { pattern: "xfinity", category: "Utilities", priority: 20 },
  { pattern: "internet", category: "Utilities", priority: 30 },
  { pattern: "water dept", category: "Utilities", priority: 25 },
  { pattern: "verizon", category: "Utilities", priority: 25 },
  { pattern: "t-mobile", category: "Utilities", priority: 25 },
  { pattern: "at&t", category: "Utilities", priority: 25 },
  { pattern: "netflix", category: "Subscriptions", priority: 20 },
  { pattern: "spotify", category: "Subscriptions", priority: 20 },
  { pattern: "hulu", category: "Subscriptions", priority: 20 },
  { pattern: "disney+", category: "Subscriptions", priority: 20 },
  { pattern: "youtube premium", category: "Subscriptions", priority: 20 },
  { pattern: "icloud", category: "Subscriptions", priority: 20 },
  { pattern: "google storage", category: "Subscriptions", priority: 20 },
  { pattern: "prime membership", category: "Subscriptions", priority: 20 },
  { pattern: "gym", category: "Health", priority: 25 },
  { pattern: "fitness", category: "Health", priority: 25 },
  { pattern: "pharmacy", category: "Health", priority: 20 },
  { pattern: "cvs", category: "Health", priority: 30 },
  { pattern: "walgreens", category: "Health", priority: 30 },
  { pattern: "dental", category: "Health", priority: 20 },
  { pattern: "amazon", category: "Shopping", priority: 40 },
  { pattern: "target", category: "Shopping", priority: 35 },
  { pattern: "walmart", category: "Shopping", priority: 35 },
  { pattern: "best buy", category: "Shopping", priority: 20 },
  { pattern: "etsy", category: "Shopping", priority: 20 },
  { pattern: "airbnb", category: "Travel", priority: 20 },
  { pattern: "airlines", category: "Travel", priority: 20 },
  { pattern: "delta air", category: "Travel", priority: 20 },
  { pattern: "united air", category: "Travel", priority: 20 },
  { pattern: "hotel", category: "Travel", priority: 25 },
  { pattern: "marriott", category: "Travel", priority: 20 },
  { pattern: "cinema", category: "Entertainment", priority: 20 },
  { pattern: "amc ", category: "Entertainment", priority: 20 },
  { pattern: "steam games", category: "Entertainment", priority: 20 },
  { pattern: "playstation", category: "Entertainment", priority: 20 },
  { pattern: "atm fee", category: "Fees & Interest", priority: 10 },
  { pattern: "overdraft", category: "Fees & Interest", priority: 10 },
  { pattern: "interest charge", category: "Fees & Interest", priority: 10 },
  { pattern: "service fee", category: "Fees & Interest", priority: 15 },
  { pattern: "foreign transaction fee", category: "Fees & Interest", priority: 10 },
];
